describe('User Flow', () => {
  beforeEach(() => {
    cy.intercept('GET', 'http://localhost:3001/api/v1/orders', {
      statusCode: 200,
      fixture: 'orders'
    })
    cy.visit('http://localhost:3000')
  })
  it('Should successfully see the homepage upon visit', () => {
    cy.get('h1')
      .should('have.text', 'Burrito Builder')
    cy.get('input')
    .should('have.attr', 'placeholder', 'Name')
      cy.get('[name="beans"]')
    .should('have.text', 'beans')
    cy.get('[name="steak"]')
      .should('have.text', 'steak')
    cy.get('[name="carnitas"]')
      .should('have.text', 'carnitas')
    cy.get('[name="sofritas"]')
      .should('have.text', 'sofritas')
    cy.get('[name="lettuce"]')
      .should('have.text', 'lettuce')
    cy.get('[name="queso fresco"]')
      .should('have.text', 'queso fresco')
    cy.get('[name="pico de gallo"]')
      .should('have.text', 'pico de gallo')
    cy.get('[name="hot sauce"]')
      .should('have.text', 'hot sauce')
    cy.get('[name="guacamole"]')
      .should('have.text', 'guacamole')
    cy.get('[name="jalapenos"]')
      .should('have.text', 'jalapenos')
    cy.get('[name="cilantro"]')
      .should('have.text', 'cilantro')
    cy.get('[name="sour cream"]')
      .should('have.text', 'sour cream')
    cy.get('.App') 
    .should('have.css', 'background-image')
    cy.get('section > :nth-child(1)')
      .should('include.text', 'Scottbeanslettucecarnitasqueso frescojalapeno')
    cy.get('section > :nth-child(2)')
      .should('include.text', 'Kaylasteakpico de gallolettucecarnitasqueso frescojalapeno')
    cy.get('section > :nth-child(3)')
      .should('include.text', 'Andrewsofritasbeanssour creamcarnitasqueso fresco')
  })
  it('Should be able to order a burrito', () => {
    cy.get('input')
      .type('Jeff')
    cy.get('[name="steak"]')
      .click()
    cy.get('[name="cilantro"]')
      .click()
    cy.get(':nth-child(15)')
      .click()
    cy.get('section > :nth-child(4)')
      .should('include.text', 'Jeffsteakcilantro')
  })  
})